### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by toobiwankenobi** [BodenmillerGroup/bbRtools#20]
I tried to install bbRtools to my conda env without success.

**First attempt**
I tried it the following way (according to the [pip install reference](https://pip.pypa.io/en/stable/reference/pip_install/#git))
`pip install git+https://github.com/BodenmillerGroup/bbRtools.git@master`

**Second attempt** 
I cloned the repo and tried to install the file by

`pip install "git+file:///home/ubuntu/Git/bbRtools"`

Both times, I get the following error message:
```
 Cloning https://github.com/BodenmillerGroup/bbRtools.git (to revision master) to /tmp/pip-req-build-2k4exjoa
  Running command git clone -q https://github.com/BodenmillerGroup/bbRtools.git /tmp/pip-req-build-2k4exjoa
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/anaconda3/envs/jupyter/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2k4exjoa/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2k4exjoa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-2k4exjoa/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/anaconda3/envs/jupyter/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-2k4exjoa/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any ideas what is causing this issue?

**Comment by votti** [comment]
`bbRtools` is an R package thus it cannot be instaled via `pip` (the python package manager).
To install it via conda:
- install R in conda
- start  an R console in the conda environment
- run the `devtools::install_github(...`(as in the readme)  from within that R

**Comment by toobiwankenobi** [comment]
Sure, but according to this [stackoverflow post](https://stackoverflow.com/questions/19042389/conda-installing-upgrading-directly-from-github) one should be able to `pip install` a github repo.

I also found this [post](https://stackoverflow.com/questions/52061664/install-r-package-from-github-using-conda) which shows how to build a conda package for a github R package. 

Also, I am not able to install `bbRtools` as explained in the readme file because I get this error message when I try to install by `devtools::install_github(...)`

```
Downloading GitHub repo RGLab/Rtsne.multicore@master
Error: Failed to install 'Rtsne.multicore' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/Rtmpfgtt9F/filee272a8c8d1a.tar.gz' -C '/tmp/Rtmpfgtt9F/remotese273bb9af0a'’ returned error code 127
```

I installed `devtools` by 
```
conda install -c conda-forge r-devtools
```
I am running my `Rstudio` from a conda env on a ubuntu (18.04) VM.

**Comment by votti** [comment]
Sure one can Python packages from Github.
But `pip` (=Pip Python Package Manager) cannot handle R packages.

**Comment by toobiwankenobi** [comment]
I see. Still doesn't solve the issue that I can't install `bbRtools` by `devtools` but that is another issue then.

**Comment by votti** [comment]
@toobiwankenobi: @installation 
This is not a `bbRtools` issue, but a misconfigured conda package causing devtools not wo work properly:
In Conda, the 'best' channel for R packages is 'r'. `conda-forge` packages should  be considered experimental and only used if `r` doesnt have the package.
Can you try to install `devtools` with `conda install -c r r-devtools `, this *should* work.

**Comment by toobiwankenobi** [comment]
Already tried that (and 3 other channels).

But I think I found the [problem]( https://stackoverflow.com/questions/25939976/how-to-check-whether-r-is-already-installed-in-ubuntu). Simultaneous installation of `r-base` and `R` is not compatible with `devtools`.

**Comment by votti** [comment]
Very curious - I just installed `bbRtools` in a brand new conda environment yesterday.

This is the environment I used:
```name: Rtestenv
channels:
  - defaults
  - r
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=mro_2
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_8
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - curl=7.65.3=hbc83047_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_8
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_8
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_8
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.65.3=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - make=4.2.1=h1bed415_1
  - mro-base=3.5.1=3
  - mro-base_impl=3.5.1=h9a62091_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_1
  - pango=1.42.4=h049681c_0
  - pcre=8.43=he6710b0_0
  - pixman=0.38.0=h7b6447c_0
  - r-assertthat=0.2.0=mro351hf348343_0
  - r-backports=1.1.2=mro351hd10c6a6_0
  - r-base64enc=0.1_3=mro351hd10c6a6_0
  - r-bh=1.66.0_1=mro351hf348343_0
  - r-bindr=0.1.1=mro351hf348343_0
  - r-bindrcpp=0.2.2=mro351hebc1506_0
  - r-broom=0.5.0=mro351hf348343_0
  - r-callr=2.0.4=mro351hf348343_0
  - r-cellranger=1.1.0=mro351hf348343_0
  - r-cli=1.0.0=mro351hf348343_0
  - r-clipr=0.4.1=mro351hf348343_0
  - r-colorspace=1.3_2=mro351hd10c6a6_0
  - r-crayon=1.3.4=mro351hf348343_0
  - r-curl=3.2=mro351hd10c6a6_1
  - r-dbi=1.0.0=mro351hf348343_0
  - r-dbplyr=1.2.2=mro351hf348343_0
  - r-devtools=1.13.6=mro351hf348343_0
  - r-dichromat=2.0_0=mro351hf348343_0
  - r-digest=0.6.15=mro351hd10c6a6_0
  - r-dplyr=0.7.6=mro351hebc1506_0
  - r-evaluate=0.11=mro351hf348343_0
  - r-fansi=0.2.3=mro351hd10c6a6_0
  - r-forcats=0.3.0=mro351hf348343_0
  - r-ggplot2=2.2.1=mro343h889e2dd_0
  - r-git2r=0.23.0=mro351hd10c6a6_1
  - r-glue=1.3.0=mro351hd10c6a6_0
  - r-gtable=0.2.0=mro351hf348343_0
  - r-haven=1.1.2=mro351hebc1506_0
  - r-highr=0.7=mro351hf348343_0
  - r-hms=0.4.2=mro351hf348343_0
  - r-htmltools=0.3.6=mro351hebc1506_0
  - r-httr=1.3.1=mro351hf348343_1
  - r-jsonlite=1.5=mro351hd10c6a6_0
  - r-knitr=1.20=mro351hf348343_0
  - r-labeling=0.3=mro351hf348343_0
  - r-lattice=0.20_35=mro351hd10c6a6_0
  - r-lazyeval=0.2.1=mro351hd10c6a6_0
  - r-lubridate=1.7.4=mro351hebc1506_0
  - r-magrittr=1.5=mro351hf348343_0
  - r-markdown=0.8=mro351hd10c6a6_0
  - r-mass=7.3_50=mro351hd10c6a6_0
  - r-memoise=1.1.0=mro351hf348343_0
  - r-mime=0.5=mro351hd10c6a6_0
  - r-modelr=0.1.2=mro351hf348343_0
  - r-munsell=0.5.0=mro351hf348343_0
  - r-nlme=3.1_137=mro351hac1494b_0
  - r-openssl=1.0.2=mro351hd10c6a6_1
  - r-pillar=1.3.0=mro351hf348343_0
  - r-pkgconfig=2.0.1=mro351hf348343_0
  - r-plogr=0.2.0=mro351hf348343_0
  - r-plyr=1.8.4=mro351hebc1506_0
  - r-praise=1.0.0=mro351hf348343_0
  - r-processx=3.1.0=mro351hebc1506_0
  - r-purrr=0.2.5=mro351hd10c6a6_0
  - r-r6=2.2.2=mro351hf348343_0
  - r-rcolorbrewer=1.1_2=mro351hf348343_0
  - r-rcpp=0.12.18=mro351hebc1506_0
  - r-readr=1.1.1=mro351hebc1506_0
  - r-readxl=1.1.0=mro351hebc1506_0
  - r-rematch=1.0.1=mro351hf348343_0
  - r-reprex=0.2.0=mro351hf348343_0
  - r-reshape2=1.4.3=mro351hebc1506_0
  - r-revoutils=11.0.0=mro351_0
  - r-revoutilsmath=11.0.0=mro351_0
  - r-rlang=0.2.1=mro351hd10c6a6_0
  - r-rmarkdown=1.10=mro351hf348343_0
  - r-rprojroot=1.3_2=mro351hf348343_0
  - r-rstudioapi=0.7=mro351hf348343_0
  - r-rvest=0.3.2=mro351hf348343_0
  - r-scales=0.5.0=mro351hebc1506_0
  - r-selectr=0.4_1=mro351hf348343_0
  - r-stringi=1.2.4=mro351hebc1506_0
  - r-stringr=1.3.1=mro351hf348343_0
  - r-testthat=2.0.0=mro351hebc1506_0
  - r-tibble=1.4.2=mro351hd10c6a6_0
  - r-tidyr=0.8.1=mro351hebc1506_0
  - r-tidyselect=0.2.4=mro351hebc1506_0
  - r-tidyverse=1.2.1=mro351hf348343_0
  - r-tinytex=0.6=mro351hf348343_0
  - r-utf8=1.1.4=mro351hd10c6a6_0
  - r-viridislite=0.3.0=mro351hf348343_0
  - r-whisker=0.3_2=mro351hf348343_0
  - r-withr=2.1.2=mro351hf348343_0
  - r-xfun=0.3=mro351hf348343_0
  - r-xml2=1.2.0=mro351hebc1506_0
  - r-yaml=2.2.0=mro351hd10c6a6_0
  - tk=8.6.8=hbc83047_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3

```
